### ISSUE TITLE
Uncaught Error: spawn ENOENT

### ISSUE THREAD

**Issue by tvooo** [kokarn/atom-grunt-runner#2]
If I don't have anything entered in the PATH field of the package's settings, I get this error message in the console: *Uncaught Error: spawn ENOENT*.

If I have a *wrong* path entered in the PATH field, I get the proper error message (as should happen for the above case, as well).

BTW: Sublime Text has this problem, and it appears to affect Atom as well. If I start Atom via iTerm (or any environment with the correct PATH), the PATH is set correctly and I don't need to set in manually. If I start Atom from Alfred or the Dock instead, this is not the case. Might be my environment, though, but in case someone comes up with the same problem, you can point them to it.

**Comment by kokarn** [comment]
@maxkorp Is this still an issue?

**Comment by maxkorp** [comment]
I don't know, unfortunately. I haven't been using grunt in a real way for 6+ months now, as I have everything automated.

**Comment by kokarn** [comment]
Hmm, i'll close this for now then. If somebody else reports it, i'll reopen. Thanks for the quick response!

**Comment by maxkorp** [comment]
:+1:  No problemo!
