### ISSUE TITLE
Can't figure out the path

### ISSUE THREAD

**Issue by lunelson** [kokarn/atom-grunt-runner#3]
It would be helpful to have an indication of what the path for grunt-cli might be. I've tried everything but no luck. I'm on OSX and installed it with `sudo npm install -g grunt-cli`

**Comment by aosi87** [comment]
I just did that and never works for me, im using atom-grunt-runer 0.11.0 with atom 1.0.2

**Comment by dubrod** [comment]
OMG was scratching my head for an hour till i found that Config file there. 

did `sudo nano` on the init.coffee, restarted Atom and bam works awesome!!
