### ISSUE TITLE
The icon does not change to an issue when the task has failed

### ISSUE THREAD

**Issue by wmonk** [kokarn/atom-grunt-runner#52]
For some reason when the grunt task exits with a non zero code it doesn't change it to use the broken icon.

**Comment by ealves-pt** [comment]
PR #69 may fix this issue.

**Comment by kokarn** [comment]
@wmonk Can you try with the latest version?

**Comment by ealves-pt** [comment]
I think PR #69 fixed this bug so I will close this issue.
