### ISSUE TITLE
Running causes devtools to open. 

### ISSUE THREAD

**Issue by eighteyes** [kokarn/atom-grunt-runner#7]
Interesting. :)

**Comment by visualcookie** [comment]
Did try your solutions... didn't worked out. Still get the same error.

**Comment by tusbar** [comment]
Same here, grunt is installed in `~/.nvm/versions/node/v0.12.2/bin`

Specifying `~/.nvm/versions/node/v0.12.2/bin` or `/Users/username/.nvm/versions/node/v0.12.2/bin` in the PATH settings still doesn't allow `grunt-runner` to find `grunt`.

**Comment by hamishtaplin** [comment]
Same here. Grunt is installed `/usr/local/bin/` but this no worky.

**Comment by kokarn** [comment]
Are you getting some error or are devtools opening?

Recently I had the problem with Atom having different paths depending on how you open it.

There is a big thread about that over here https://github.com/AtomLinter/Linter/issues/150 but the solution for me and some others was to add all the paths from ```$PATH``` to ```init.coffee```.

This is now my ```init.coffee```
```
# Your init script
#
# Atom will evaluate this file each time a new window is opened. It is run
# after packages are loaded/activated and after the previous editor state
# has been restored.
#
# An example hack to make opened Markdown files always be soft wrapped:
#
# path = require 'path'
#
# atom.workspaceView.eachEditorView (editorView) ->
#   editor = editorView.getEditor()
#   if path.extname(editor.getPath()) is '.md'
#     editor.setSoftWrap(true)

process.env.PATH = [
        '/usr/local/bin',
        '/usr/bin'
        '/bin',
        '/usr/sbin',
        '/sbin'
    ].join( ':' );
```

**Comment by hamishtaplin** [comment]
@kokarn Running Atom via the command line does indeed fix the problem.

**Comment by miketierney** [comment]
I'll pitch in that @kokarn's workaround fixed it for me (so far only tested after launching via the command line).
