### ISSUE TITLE
Support multiple Gruntfiles (multiple projects in same window)

### ISSUE THREAD

**Issue by tehsenaus** [kokarn/atom-grunt-runner#76]
I like to have multiple projects open in the same Atom window, by adding multiple folders to the Atom 'project'. It would be nice if the grunt runner supported this, by using the Gruntfile nearest to the file I have open.

**Comment by tenKinetic** [comment]
I added a pull request for this. It's working for me with projects side-by-side / in the same window, hopefully for others too.

**Comment by kokarn** [comment]
This is now merged and published to APM.
