### ISSUE TITLE
Moving atom-grunt-runner to kokarn

### ISSUE THREAD

**Issue by nickclaw** [kokarn/atom-grunt-runner#80]
Hi @kokarn, sorry I've been missing in action. I've (clearly) stopped using atom-grunt-runner personally, and I'd like to transfer ownership of the repo and apm package to you if you want it. Let me know!

**Comment by kokarn** [comment]
Hey! 
No worries, stuff happens, it's life.
Hmm, i'm not that versed in coffeescript so I might not be the ideal maintainer but i'm here and won't go missing so maybe that's good enough for now? 
Then if somebody steps up and want's to take over, it's easier to just transfer it to them.

What do you need from me?

**Comment by nickclaw** [comment]
Yeah, well thanks for keeping track of all the issues for so long! I just wanted some confirmation from you, I'll transfer it over now.

I'm pretty sure this should give you [control over the apm package](https://atom.io/docs/latest/behind-atom-maintaining-your-packages#transferring-ownership), but if it doesn't let me know.

**Comment by nickclaw** [comment]
Ooh, actually you'll need to delete your fork first. I can't transfer it over while there's a repo with the same name under your account.

**Comment by kokarn** [comment]
Fork deleted!

**Comment by nickclaw** [comment]
Transferring! I'm not sure if you have to confirm it or if it's just taking a while. But I'll check back in the morning.

**Comment by nickclaw** [comment]
Hmm.. Still transferring.. @kokarn do you see any way to confirm the transfer?

**Comment by kokarn** [comment]
Sorry! It got lost in the mail. Should be done now?

**Comment by ealves-pt** [comment]
Cool :+1: I'm happy to "hear" this news.

**Comment by kokarn** [comment]
Apparently you need to transfer it again @nickclaw. I was too slow :(

**Comment by nickclaw** [comment]
Started the transfer over, hopefully it'll work now!

**Comment by kokarn** [comment]
It does indeed ;)

**Comment by nickclaw** [comment]
![](http://i.imgur.com/z94yPSH.gif)

Excellent, you should automatically have control over the package in `apm` too, but I'd double check :P

**Comment by kokarn** [comment]
Looks to be working wonders. Thanks!
