### ISSUE TITLE
After update to 0.13.0 stopped to run and find tasks

### ISSUE THREAD

**Issue by tclemos** [kokarn/atom-grunt-runner#82]
As the subject describes, after the update to version 0.13.0 this morning I'm currently unable to run grunt tasks from this package, the box to type the task name appears, but there is no tasks and even if I type a task that I'm really sure that is configured properly into gruntfile.js, it doesn't worked. Something similar had happened to me before when I forgot to install grunt, but now this is not the case. It looks like the package can't finding the gruntfile.

I've tried:
Downgraded Atom to 1.4.3, doesn't fixed(the atom 1.5.0 is facing problems with git statuses)
Changed the gruntfile.js name to gruntfile(without .js extension), doesn't fixed
Reinstalled grunt, doesn't fixed
Downgraded grunt-runner package from 0.13.0 to 0.11.0, FIXED!!!

I realized that you have added a new feature specifically for gruntfile paths, so probably the problem is there, I don't know if this problem can be related with the Atom git statuses that looks to be a path problem too.

I will continue to work with the 0.11.0 version until it get fixed.

**Comment by kokarn** [comment]
Can you post your Gruntfile and anything special you have configured on your system? 
I think it's related to either #79 or #70

**Comment by tclemos** [comment]
There is nothing special configured in my system, I'm running Windows 10 and the problem happened in Atom 1.4.3 and 1.5.0 when running the 0.13.0 version, it worked fine in both atom versions when using the 0.11.0.

**Comment by ealves-pt** [comment]
I was checking that problem because I'm having the same issue with this new version and I was trying to debug it.

**Comment by ealves-pt** [comment]
Locally I have reverted the code from PR #79 and the gruntfile is detected. @kokarn should we release a version 0.13.1 with that PR out?

**Comment by ealves-pt** [comment]
I have opened the PR #83 to revert that commit and I have bumped the version number.

**Comment by kokarn** [comment]
Merged! Publishing to apm ASAP

**Comment by tclemos** [comment]
I've already downloaded de version 0.13.2 and now it seems to work fine.

Thanks for the quick fix!!!!

**Comment by ealves-pt** [comment]
:+1:
