### ISSUE TITLE
After Disable and Enable cause the package to create a new panel

### ISSUE THREAD

**Issue by tclemos** [kokarn/atom-grunt-runner#84]
Steps to reproduce:

1. Show the Panel (grunt-runner:toggle-panel)
2. Go to Atom -> Settings -> Packages
3. Go to grunt-runner package and click on Disable, then click Enable.

After these steps a new panel will be created and every time you execute the following steps, a new one will be created, if you hide the current panel and execute the following steps again, you will have an alternated state to the new panel.

Even with more the one panel, only the first shows the output from grunt.

**Comment by ealves-pt** [comment]
@tclemos I was digging through the code to become more familiarized with it and I think I have found the cause of this bug.

I think I have it fixed locally and I will test it during the day and if everything is fine I will open a PR.

**Comment by ealves-pt** [comment]
@tclemos can you clone the repo and test locally if the version in the master solves your problem?

**Comment by tclemos** [comment]
@ealves-pt Sure.

I've already cloned and the problem was fixed.

Thank you very much! :+1:

**Comment by ealves-pt** [comment]
Nice. I will revert the indentation changes and then it will be finished. :+1:
